#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri May 08 11:31:01 EDT 2026
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1778254261141
maven-metadata-gitea-repo.xml.error=
maven-metadata-gitea-repo.xml.lastUpdated=1778254261148
