#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Apr 20 13:33:31 EDT 2026
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1776706411091
maven-metadata-gitea-repo.xml.error=
maven-metadata-gitea-repo.xml.lastUpdated=1776706411092
